In [1]:
import xml.etree.ElementTree as ET
import pandas as pd
import os
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw
import configs as cfg

In [2]:
# dir_xmls = os.path.join(cfg.train_Dir, "annotations/xmls/")
# dir_imgs =  os.path.join(cfg.train_dir, "images")

# annotations = os.listdir(dir_xmls)
# images = os.listdir(dir_imgs)

In [3]:
# index = 11
# tree = ET.parse(dir_xmls + annotations[index])
# root = tree.getroot()

# objects = root.findall("object")
# names, poses, truncates, difficulties = [],[],[],[]
# xmin, ymin, xmax, ymax = [],[],[],[]

# for obj in objects:
#     names.append(obj.find("name").text)
#     poses.append(obj.find("pose").text)
#     truncates.append(obj.find("truncated").text)
#     difficulties.append(obj.find("difficult").text)
    
#     bboxes = obj.find("bndbox")
#     xmin.append(int(bboxes.find("xmin").text))
#     ymin.append(int(bboxes.find("ymin").text))
#     xmax.append(int(bboxes.find("xmax").text))
#     ymax.append(int(bboxes.find("ymax").text))
    
# I = Image.open(dir_imgs + images[index])
# Idraw = ImageDraw.Draw(I)

# for x0, y0, x1, y1, name in zip(xmin, ymin, xmax, ymax, names):
#     Idraw.rectangle([(x0, y0), (x1, y1)], outline='yellow')
#     Idraw.text((x0+2, y0+1), name, fill=(0,0,0))

# plt.figure(figsize=(10,10))
# plt.title(images[index])
# plt.imshow(I)
# plt.axis('off')
# plt.show()

In [4]:
# create_list.py (prototype)

dir_xmls = os.path.join(cfg.train_dir, "annotations", "xmls")
dir_imgs = os.path.join(cfg.train_dir, "images")

annotations = [os.path.join(dir_xmls, xml) for xml in os.listdir(dir_xmls)]
images = [os.path.join(dir_imgs, img) for img in os.listdir(dir_imgs)]

dataset = []
# make panda DataFrame that consist of : filename, objectID, name, xmin, ymin, xmax, ymin
for i, annotation in enumerate(annotations):
    
    filename = images[i]
    tree = ET.parse(annotation)
    objects = tree.findall("object")
    
    for i, obj in enumerate(objects):
        objectID = "object_{:02d}".format(i)
        name = obj.find("name").text
        
        bbox = obj.find("bndbox")
        xmin = bbox.find("xmin").text
        ymin = bbox.find("ymin").text
        xmax = bbox.find("xmax").text
        ymax = bbox.find("ymax").text

        temp = [filename, objectID, name, xmin, ymin, xmax, ymax]
        dataset.append(temp)

df = pd.DataFrame(dataset, columns=["filename", "objectID", "name", "xmin", "ymin", "xmax", "ymax"])
df.to_csv(cfg.dataset_name, index=False)

In [5]:
df.tail(20)

,filename,objectID,name,xmin,ymin,xmax,ymax
4907,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,435,2,511,75
4908,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D00,1,208,35,298
4909,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D20,149,212,454,512
4910,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,1,103,501,252
4911,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D00,3,256,51,512
4912,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,348,127,387,268
4913,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D10,271,269,356,300
4914,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_02,D10,1,325,307,363
4915,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_03,D00,357,269,468,508
4916,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,4,302,512,435
4917,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,1,225,153,491
4918,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D00,15,113,82,347
4919,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D10,85,239,512,349
4920,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_02,D00,391,334,470,512
4921,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_03,D00,1,345,83,500
4922,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,Repair,1,26,512,330
4923,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D10,258,264,437,281
4924,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D10,450,295,512,318
4925,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_02,D00,462,143,512,220
4926,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D10,1,246,512,333

In [6]:
dtset = pd.read_csv(cfg.dataset_name)

In [7]:
dtset.head()

,filename,objectID,name,xmin,ymin,xmax,ymax
0,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,Repair,141,64,512,512
1,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_01,D20,169,1,512,180
2,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_02,D20,419,180,512,295
3,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_03,D00,124,1,148,45
4,D:/Dataset/CRDDC2022/dataset/China_MotorBike/t...,object_00,D40,203,214,238,294

In [8]:
len(df)

4927

In [14]:
# Uji Coba Dataset
import configs as cfg
from dataset import RoadDamageDataset

RDD = RoadDamageDataset(cfg.dataset_name)

In [15]:
len(RDD)

4927

In [16]:
cat_name_to_id = {
    "D00" : 1,
    "D10" : 2,
    "D20" : 3,
    "D40" : 4,
    "Repair" : 5,
    }

In [17]:
import torch

torch.LongTensor(cat_name_to_id["D00"])

tensor([0])

In [18]:
image, bbox, label = RDD[0]

In [19]:
bbox

tensor([141.,  64., 512., 512.])

In [20]:
label

tensor(5.)